app:
  name: cloud-computing-final-project
  port: 8080
  image:
    name: cloud-computing-final-project
    tag: v3
    pullPolicy: IfNotPresent
  svc:
    name: cloud-computing-final-project-service
    type: LoadBalancer
    port: 8080
  conf:
    name: app-conf
    master_service: master-svc
    slave_service: slave-svc
    master_url: jdbc:postgresql://master-svc:5432/postgres
    slave_url: jdbc:postgresql://slave-svc:5432/postgres
    port: 8080
    master_user: user
    master_password: password
    slave_user: user
    slave_password: password


postgresql:
  image:
    name: postgres
    tag:  14-alpine
  pv:
    name: postgres-persistent-volume
  master:
    host: master-postgres
    port: 5432
    database: postgres
    username: user
    password: password
    initScript: files/00_init.sql
    svc:
      name: master-svc
    pvc:
      name: master-pvc
    conf:
      name: master-conf
  slave:
    host: slave-postgres
    port: 5432
    database: postgres
    username: user
    password: password
    pvc:
      name: slave-pvc
    svc:
      name: slave-svc
    conf:
      name: slave-conf