apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.svc.name }}
spec:
  type: {{ .Values.app.svc.type }}
  ports:
    - port: {{ .Values.app.svc.port }}
      targetPort: {{ .Values.app.svc.port }}
  selector:
    app: {{ .Values.app.name }}