apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-computing-final-project.fullname" . }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.port }}
  selector:
    app: {{ include "cloud-computing-final-project.name" . }}