apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-master-configmap
  labels:
    app: postgres-master-configmap
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
  POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"