apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-master
spec:
  serviceName: postgres-master
  replicas: 1
  selector:
    matchLabels:
      app: postgres-master
  template:
    metadata:
      labels:
        app: postgres-master
    spec:
      containers:
        - name: postgres-master
          image: postgres:14-alpine
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.postgresql.master.database }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgresql.master.username }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgresql.master.password }}"
          ports:
            - containerPort: 5432