apiVersion: v1
kind: Service
metadata:
  name: postgres-master
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-master

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-slave
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-slave