apiVersion: v1
kind: Service
metadata:
  name: postgres-master
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30001
  selector:
    app: postgres-master

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-slave
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30002
  selector:
    app: postgres-slave