apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloud-computing-final-project.fullname" . }}-init-sql
data:
  init.sql: |
{{ .Files.Get .Values.postgresql.master.initScript | nindent 4 }}