apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.master.svc.name }}
  labels:
    app: {{ .Values.postgresql.master.svc.name }}
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30001
      protocol: TCP
  selector:
    app: {{ .Values.postgresql.master.host }}
