apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-master
  labels:
    component: postgres-master
spec:
  selector:
    matchLabels:
      component: postgres-master
  template:
    metadata:
      labels:
        component: postgres-master
    spec:
      containers:
        - name: postgres
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-master-configmap
          args:
            - "postgres"
            - "-c"
            - "wal_level=replica"
            - "-c"
            - "hot_standby=on"
            - "-c"
            - "max_wal_senders=10"
            - "-c"
            - "max_replication_slots=10"
            - "-c"
            - "hot_standby_feedback=on"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data-master
            - name: init-sql
              mountPath:  /docker-entrypoint-initdb.d
      volumes:
        - name: init-sql
          configMap:
            name: {{ include "cloud-computing-final-project.fullname" . }}-init-sql
        - name: postgres-data-master
          persistentVolumeClaim:
            claimName: master-pvc
