apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-storage
  labels:
    app: pv-storage
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/db

