apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgresql.pv.name }}
  labels:
    app: {{ .Values.postgresql.pv.name }}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/db

