apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{  .Values.postgresql.slave.pvc.name  }}
  labels:
    app: {{ .Values.postgresql.slave.pvc.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi