apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgresql.slave.conf.name }}
  labels:
    app: {{ .Values.postgresql.slave.conf.name }}
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  POSTGRES_MASTER_SERVICE_HOST: "{{  .Values.postgresql.master.host  }}"
  PGUSER: "replicator"
  PGPASSWORD: "replicator_password"